# site settings
title: Leicestershire Matters
subtitle: Digital digest 2017
email:
description: Welcome to the Summer 2017 edition
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: County Hall, Glenfield
city: Leicester
state: Leicestershire
zip_code: LE38RA
country: United Kingdom
phone:

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://uk.linkedin.com/company/leicestershire-county-council
pinterest_url:
slack_url:
twitter_url: https://twitter.com/leicscountyhall

# build settings
markdown: kramdown

sass:
  style: compressed
